### ISSUE TITLE
Check if node meta data will be deleted on node digging

### ISSUE THREAD

**Issue by nics-le** [xenurine-minetest/Beer_Test#11]
If not it may lead to unexpected behaviour

**Comment by xenurine** [comment]
Yes, on removing the node, i think it will be best to remove all data when its removed. 

We can add some protection, so the block cannot be removed if items or beer is in the barrel.

**Comment by nics-le** [comment]
Implementing protection should be easy. But I think you misunderstood me. The question is not if metadata should be deleted on node removal. The question is if they got removed automatically or if I have to add some code for it.

**Comment by nics-le** [comment]
just tested: metadata of a node got destroyed as soon node is removed. So we can close this issue
